baseURL = "https://razahai.github.io"
languageCode = "en-us"
title = "razahai"

enableRobotsTXT = true

defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
unsafe = true

[params]
title = "razahai"
short_description = "engineer"

[params.author]
name = "raza"